# ruby encoding: utf-8
Volumetric.create!(:coefficient=>5000, :updated_by=>'shuhail', :status=>true, :comments=>'Base Caculation', :name=>'VOLUMETRIC_COFF')
Volumetric.create!(:coefficient=>0.25, :updated_by=>'shuhail', :status=>true, :comments=>'Base Calculation', :name=>'DISTANCE_COEFF')
Volumetric.create!(:coefficient=>500, :updated_by=>'shuhail', :status=>true, :comments=>'Base weight for base calculatoin', :name=>'BASE_WEIGHT')
Volumetric.create!(:coefficient=>75, :updated_by=>'shuhail', :status=>true, :comments=>'Base weight charge', :name=>'BASE_WEIGHT_CHARGE')
Volumetric.create!(:coefficient=>1, :updated_by=>'shuhail', :status=>true, :comments=>'extra weight', :name=>'EXTRA_WEIGHT')
Volumetric.create!(:coefficient=>0.025, :updated_by=>'shuhail', :status=>true, :comments=>'extra weigh extra charge', :name=>'EXTRA_WEIGHT_CHARGE')
Volumetric.create!(:coefficient=>0, :updated_by=>'shuhail', :status=>true, :comments=>'Insurance charge', :name=>'INSURANCE_PERCENT')
Volumetric.create!(:coefficient=>0, :updated_by=>'shuhail', :status=>true, :comments=>'Risk Charge', :name=>'RISK_CHARGE')
Volumetric.create!(:coefficient=>15, :updated_by=>'shuhail', :status=>true, :comments=>'Service Charge', :name=>'SERVICE_CHARGE')
Volumetric.create!(:coefficient=>15, :updated_by=>'shuhail', :status=>true, :comments=>'Service Tax', :name=>'SERVICE_TAX')
Volumetric.create!(:coefficient=>15, :updated_by=>'shuhail', :status=>true, :comments=>'Service Tax', :name=>'PICKUP_CHARGE')
Volumetric.create!(:coefficient=>300, :updated_by=>'shuhail', :status=>true, :comments=>'Service Tax', :name=>'BASE_DISTANCE')
Volumetric.create!(:coefficient=>125, :updated_by=>'shuhail', :status=>true, :comments=>'Service Tax', :name=>'BASE_DISTANCE_CHARGE')
Volumetric.create!(:coefficient=>0, :updated_by=>'shuhail', :status=>true, :comments=>'C/N Charge', :name=>'C_N_CHARGE')
Volumetric.create!(:coefficient=>0, :updated_by=>'shuhail', :status=>true, :comments=>'EDL Charge', :name=>'EDL_CHARGE')
Volumetric.create!(:coefficient=>0, :updated_by=>'shuhail', :status=>true, :comments=>'FUEL SURCHARGE', :name=>'FUEL_SURCHARGE')
Volumetric.create!(:coefficient=>15, :updated_by=>'shuhail', :status=>true, :comments=>'PICKUP CHARGE', :name=>'PICKUP_CHARGE')
